### ISSUE TITLE
6_lstm

### ISSUE THREAD

**Issue by ksindi** [ponderousmad/ud730#1]
Thanks for your notebooks. Did you ever figure out solving Assignment 6 Problem 2?
I think the issue might be with `labels =  np.concatenate(list(batches)[1:])` as I get the error: 

```
ValueError: operands could not be broadcast together with shapes (320,) (320,8) 
```

I might have solved it with:

```
labels =  np.concatenate(embedding_normalized.eval()[list(batches)[1:], :])
```

But now the issue is:

```
     43                         prediction = sample_prediction.eval(
---> 44                             {sample_input: feed})
...
ValueError: Cannot feed value of shape (1, 27) for Tensor u'Placeholder_6:0', which has shape '(1,)'
```

Not sure if we'd have to also change `sample` as well.

**Comment by ponderousmad** [comment]
I realized that I wasn't sure If I was even heading in the right direction - the assignment was (possibly deliberately) a bit vague in terms of how you were meant to use bigrams, so I set it aside (my current projects don't involve LSTMs and are more focused on convnets). I'll probably come back to it at some point, but probably not any time soon.
